# Generated by Django 3.2.8 on 2021-10-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBudgets',
            fields=[
                ('a_shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_month', models.DateField()),
                ('a_budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 't_budgets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TShops',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=255)),
                ('a_online', models.IntegerField()),
                ('a_offline', models.IntegerField()),
                ('a_notification', models.IntegerField()),
            ],
            options={
                'db_table': 't_shops',
                'managed': False,
            },
        ),
    ]
